### ISSUE TITLE
Prototool should not override configured import_path

### ISSUE THREAD

**Issue by linzhp** [uber/prototool#186]
We have a prototool.yaml look like this:

```yaml
protoc:
  version: 3.6.1
generate:
  go_options:
    import_path: code.uber.internal/ua3/domain/.gen/proto/go
  plugins:
   - name: gogoslick
     type: gogo
     output: ../all_proto
   - name: yarpc-go
     type: gogo
     output: ../all_proto
```

After running `prototool/generate`, it produces imports in Go files looks like this: 
```Go
import domain "code.uber.internal/ua3/domain/.gen/proto/all_proto/ua3/domain"
```
We expect it should be 

```Go
import domain "code.uber.internal/ua3/domain/.gen/proto/go/ua3/domain"
```

The issue is that prototool replaces the last part of import_path in the YAML file ("go") with the last part of output directory ("all_proto") before appending the rest of the package import path.

@peter-edge

**Comment by peter-edge** [comment]
You're not using the `import_path` correctly - per the comment on the [example file](https://github.com/uber/prototool/blob/dev/etc/config/example/prototool.yaml#L68), "this should be the go path of the prototool.yaml file.". You're pointing it to the generated code location. If your prototool.yaml file is in `idl/code.uber.internal`, the `import_path` should be `code.uber.internal/ua3/domain/idl.code.uber.internal`. If your `prototool.yaml` file is in the root of the repository, it should be `code.uber.internal/ua3/domain`.

**Comment by peter-edge** [comment]
So assuming your prototool.yaml is at `idl/code.uber.internal/prototool.yaml`, this is what it would be:

```yaml
protoc:
  version: 3.6.1
generate:
  go_options:
    import_path: code.uber.internal/ua3/domain/idl/code.uber.internal
  plugins:
   - name: gogoslick
     type: gogo
     output: ../../.gen/proto/go
   - name: yarpc-go
     type: gogo
     output: ../../.gen/proto/go
```
