### ISSUE TITLE
Prototool is generating too long line

### ISSUE THREAD

**Issue by dysosmus** [uber/prototool#187]
I trying to update to prototool from `v0.3.0` to `v0.7.0` and it seems that new version is generating too long line.
 I'm getting the error:

```
fork/exec /Users/xxx/Library/Caches/prototool/Darwin/x86_64/protobuf/3.6.1/bin/protoc: argument list too long
``` 

When running `prototool generate .` .

Version:
```
$ prototool version
Version:                 0.7.0
Default protoc version:  3.6.1
Go version:              go1.10.3
OS/Arch:                 darwin/amd64
```

**Comment by peter-edge** [comment]
We need more info than that to debug this - is the repository where `prototool` called OSS? Can you provide the `prototool.yaml` file? Regardless, can you provide the output of `prototool generate --debug`?

**Comment by dysosmus** [comment]
The repository isn't OSS but I can provide the [debug output](https://github.com/uber/prototool/files/2287731/debug.out.txt) and the prototool.yaml 

````yaml
protoc:
  # The Protobuf version to use from https://github.com/google/protobuf/releases.
  # Set this to make your builds completely reproducible.
  allow_unused_imports: false
  # Additional paths to include with -I to protoc.
  # By default, the directory of the config file is included,
  # or the current directory if there is no config file.
  includes:
  - ./vendor/github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis

# Paths to exclude when using directory mode.
# These are prefixes, not regexes, so path/to/a will ignore anything beginning with
# $(dirname some/dir/prototool.yaml)/path/to/a including for example $(dirname some/dir/prototool.yaml)/path/to/ab.
excludes:
- build
- doc
- template
- vendor
- .git

lint:
  rules:
    no_default: true
    add:
      - COMMENTS_NO_C_STYLE
      - FILE_OPTIONS_GO_PACKAGE_SAME_IN_DIR
      - FILE_OPTIONS_JAVA_PACKAGE_SAME_IN_DIR
      - FILE_OPTIONS_REQUIRE_GO_PACKAGE
      - FILE_OPTIONS_REQUIRE_JAVA_PACKAGE
      - MESSAGE_FIELD_NAMES_LOWER_SNAKE_CASE
      - MESSAGE_NAMES_CAMEL_CASE
      - MESSAGE_NAMES_CAPITALIZED
      - ONEOF_NAMES_LOWER_SNAKE_CASE
      - PACKAGE_LOWER_SNAKE_CASE
      - PACKAGES_SAME_IN_DIR
      - RPC_NAMES_CAMEL_CASE
      - RPC_NAMES_CAPITALIZED
      - SERVICE_NAMES_CAMEL_CASE
      - SERVICE_NAMES_CAPITALIZED
      - SYNTAX_PROTO3
      - WKT_DIRECTLY_IMPORTED

generate:
  go_options:
    import_path: Fo4voh.ievah5aeF1a.On/supportive/protobuf
    extra_modifiers:
        google/api/annotations.proto: google.golang.org/genproto/googleapis/api/annotations
        google/api/http.proto: google.golang.org/genproto/googleapis/api/annotations
  plugins:
  - name: go
    type: go
    flags: plugins=grpc
    output: ../protobuf

  - name: grpc-gateway
    type: go
    output: ../protobuf

  - name: java
    output: ../protobuf-gen-java/src/main/java
  
  - name: python
    flags: plugins=grpc
    output: ../protobuf-gen-python/messagebird/protobuf

```

**Comment by peter-edge** [comment]
Does `python_out` support `plugins=grpc`? I think that is a Golang-only flag. Can you confirm this worked for v0.3.0?

**Comment by peter-edge** [comment]
Note `allow_unused_imports: false` is the default value so you don't need to include this in the `prototool.yaml` file :-)

**Comment by peter-edge** [comment]
Also your `excludes` - are these directories underneath the directory that the `prototool.yaml` file is in? It seems that the `prototool.yaml` file is not in the root of the respository, so these can probably be removed too :-) The `excludes` list is for directories/files within the directory the `prototool.yaml` file is in.

**Comment by dysosmus** [comment]
```
Does python_out support plugins=grpc? I think that is a Golang-only flag. 
```
The `plugins=grpc` is indeed a copy-paste error it shouldn't be there but that do not change much to the bug.  

```
Can you confirm this worked for v0.3.0?
```
It was working perfectly under `v0.3.0`. 

```
Also your excludes - are these directories underneath the directory that the prototool.yaml file is in?
```
The `prototool.yaml` is a the root of the repository. The listed directories in `excludes` are at the same than `prototool.yaml` not excluding them, in `v.0.3.0` was leading prototool trying to search `*.proto` in there.  Do the behaviour of `excludes ` changed?

**Comment by peter-edge** [comment]
Run the protoc commands from —dry-run manually, do you see the same issue? From glancing at the debug output, it’s not immediately apparent what the problem is, other than the python_out issue.

**Comment by dysosmus** [comment]
To simplify a bit I've the exact same bug with that minimal `prototool.yaml`

```yaml
protoc:
  includes:
  - ./vendor/github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis

excludes:
- build
- doc
- template
- vendor
- .git

generate:
  go_options:
    import_path: Fo4voh.ievah5aeF1a.On/supportive/protobuf
  plugins:
  - name: go
    type: go
    output: ../protobuf
```

Running `prototool generate --dry-run .` emits 18 commands and every command returns `Argument list too long` when manually run.
