### ISSUE TITLE
protoc flags: `--descriptor_set_out` and `--include_imports`

### ISSUE THREAD

**Issue by angrz** [uber/prototool#211]
How to use `protoc` flags e.g. `--descriptor_set_out=` and `--include_imports` ?

**Comment by peter-edge** [comment]
This should work out of the box.

`descriptor_set_out` can be treated as a plugin in the `generate` section, similar to `java`:

```yml
generate:
  plugins:
    - name: descriptor_set
      output: gen/descriptor_set
```

`--include_imports` is implicitly called, so nothing needs to be done there.
