### ISSUE TITLE
Abstract class missing in compiled .proto files

### ISSUE THREAD

**Issue by whisper-bye** [uber/prototool#218]
my prototool.yaml

```
protoc:
  version: 3.6.1
generate:
  plugins:
    - name: java
      output: ../src/main/java/
```

miss *ImplBase java abstract class
