### ISSUE TITLE
GRPC Python Output

### ISSUE THREAD

**Issue by ksbeking** [uber/prototool#239]
This is a feature request regarding using prototool to generate python grpc files (I think). It is currently able to do so for the type definitions with the following configuration. 

```
  - name: python
    output: ../../gen/python
```

However, generating the GRPC files seems impossible to me at this point in time. Being able to generate both would be really useful for using python in a GRPC environment and generating the stubs. The following command is taken from the grpc website and shoes the generation command. 

```
python -m grpc_tools.protoc -I../../protos --python_out=. --grpc_python_out=. ../../protos/route_guide.proto
```

It may be wise to document an example of stub generation with Python.

In any case. Thank you for prototool! It is great!

**Comment by AlexAPB** [comment]
Looks like you just need to have an additional plugin specified in your `prototool.yaml`

```
 - name: grpc_python
    output: ../../gen/python
```

Can you confirm that this supports your use case?

**Comment by ksbeking** [comment]
I am receiving the following error.
```
<input>:1:1:protoc-gen-grpc_python failed with status code 1.
<input>:1:1:protoc-gen-grpc_python not found or is not executable.
```

Could it be related to this [grpc issue](https://github.com/grpc/grpc/issues/4961)?

**Comment by AlexAPB** [comment]
All `protoc` plugins are expected to be available from your path so if you cannot run `protoc-gen-grpc-python_out` you may not have it installed.

> Could it be related to this grpc issue?
Could be, can you try and report back?

**Comment by ksbeking** [comment]
I have tried and it doesn't work. I was worried I was in a python venv when installing the grpcio-tools but that does not seem to have solved it. Have installed grpcio-tools on the root python versions on mac and it does not work. Also tried it in ubuntu.

In any case, does prototool not handle installing protoc?

**Comment by ksbeking** [comment]
Hi Alex,

Sorry for taking a while to get back to you. The output from the generate command with the prototool is as following. I have added the prototool.yaml file at the end in case that is of any help.

```
cd proto/idl/tumelo && prototool generate
<input>:1:1:protoc-gen-grpc_python failed with status code 1.
<input>:1:1:protoc-gen-grpc_python failed with status code 1.
<input>:1:1:protoc-gen-grpc_python failed with status code 1.
<input>:1:1:protoc-gen-grpc_python failed with status code 1.
<input>:1:1:protoc-gen-grpc_python failed with status code 1.
<input>:1:1:protoc-gen-grpc_python failed with status code 1.
<input>:1:1:protoc-gen-grpc_python failed with status code 1.
<input>:1:1:protoc-gen-grpc_python failed with status code 1.
<input>:1:1:protoc-gen-grpc_python not found or is not executable.
<input>:1:1:protoc-gen-grpc_python not found or is not executable.
<input>:1:1:protoc-gen-grpc_python not found or is not executable.
<input>:1:1:protoc-gen-grpc_python not found or is not executable.
<input>:1:1:protoc-gen-grpc_python not found or is not executable.
<input>:1:1:protoc-gen-grpc_python not found or is not executable.
<input>:1:1:protoc-gen-grpc_python not found or is not executable.
<input>:1:1:protoc-gen-grpc_python not found or is not executable.
make: *** [proto_gen] Error 255
```





```yaml
protoc:
  version: 3.6.1
  # Does not allow unused imports
  allow_unused_imports: false
  includes:
  # note vendor is .gitignored
  - ../../../vendor/github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis

lint:
  rules:
    no_default: true
    add:a
    - COMMENTS_NO_C_STYLE
    - ENUMS_HAVE_COMMENTS
    - ENUMS_NO_ALLOW_ALIAS
    - ENUM_FIELD_NAMES_UPPERCASE
    - ENUM_FIELD_NAMES_UPPER_SNAKE_CASE
    - ENUM_FIELD_PREFIXES
    - ENUM_NAMES_CAMEL_CASE
    - ENUM_NAMES_CAPITALIZED
    - ENUM_ZERO_VALUES_INVALID
    - FILE_OPTIONS_EQUAL_GO_PACKAGE_PB_SUFFIX
    - FILE_OPTIONS_GO_PACKAGE_SAME_IN_DIR
    - FILE_OPTIONS_REQUIRE_GO_PACKAGE
    - MESSAGES_HAVE_COMMENTS
    - MESSAGES_HAVE_COMMENTS_EXCEPT_REQUEST_RESPONSE_TYPES
    - MESSAGE_FIELDS_NOT_FLOATS
    - MESSAGE_FIELD_NAMES_LOWERCASE
    - MESSAGE_FIELD_NAMES_LOWER_SNAKE_CASE
    - MESSAGE_NAMES_CAMEL_CASE
    - MESSAGE_NAMES_CAPITALIZED
    - ONEOF_NAMES_LOWER_SNAKE_CASE
    - PACKAGES_SAME_IN_DIR
    - PACKAGE_IS_DECLARED
    - PACKAGE_LOWER_SNAKE_CASE
    - REQUEST_RESPONSE_NAMES_MATCH_RPC
    - REQUEST_RESPONSE_TYPES_IN_SAME_FILE
    - REQUEST_RESPONSE_TYPES_UNIQUE
    - RPCS_HAVE_COMMENTS
    - RPC_NAMES_CAMEL_CASE
    - RPC_NAMES_CAPITALIZED
    - SERVICES_HAVE_COMMENTS
    - SERVICE_NAMES_CAMEL_CASE
    - SERVICE_NAMES_CAPITALIZED
    - SYNTAX_PROTO3
    - WKT_DIRECTLY_IMPORTED
  ignores:
  - id: MESSAGE_FIELDS_NOT_FLOATS
    files:
    - instrumentdata/instrumentdata.proto

generate:
  go_options:
    import_path: gitlab.com/hedge_app/mono/proto/idl/tumelo
    extra_modifiers:
      google/api/annotations.proto: google.golang.org/genproto/googleapis/api/annotations
      google/api/http.proto: google.golang.org/genproto/googleapis/api/annotations
  plugins:
  - name: go
    type: go
    flags: plugins=grpc
    output: ../../gen/go
  - name: grpc-gateway
    type: go
    output: ../../gen/go
  - name: python
    output: ../../gen/python
  - name: grpc_python
    output: ../../gen/python
```
