### ISSUE TITLE
Feature request: Ability to limit specific plugins to parts of directory tree

### ISSUE THREAD

**Issue by andviro** [uber/prototool#350]
I'd like to have an option to apply certain plugins only to specific parts of protobuf repository tree. There are for example .proto files that describe services that meant for generation of API gateways and/or Swagger definitions. In addition, each of this .proto's relies on separate config.yml file. While certainly doable, running `generate` on all files and cleaning up afterwards seems a bit messy. I propose to add `directory` option to the plugin configuration. Like this:

```yaml
generate:
  plugins:
    - name: gogo
      type: gogo
      flags: plugins=grpc
      directory: services/grpc
      output: ../gen/grpc
    - name: swagger
      type: go
      directory: services/http/v1
      flags: logtostderr=true,grpc_api_configuration=services/http/v1/config.yaml
      output: ../gen/assets

    - name: swagger
      type: go
      directory: services/http/v2
      flags: logtostderr=true,grpc_api_configuration=services/http/v2/config.yaml
      output: ../gen/assets
```
