### ISSUE TITLE
Stub files not getting generated for java

### ISSUE THREAD

**Issue by abnair24** [uber/prototool#359]
Below is my prototool.yaml

```
protoc:
  version: 3.6.1

generate:
  # Options that will apply to all plugins of type go and gogo.
   go_options:
     import_path: ./proto
   
   plugins:
   - name: java 
     output: ./model/proto/java
```
This generates requests and response classes but not the stub.
Can someone help me on this.
