### ISSUE TITLE
Custom lint groups

### ISSUE THREAD

**Issue by maguro** [uber/prototool#383]
It would be nice if there was a way to create custom lint groups.  Maybe `prototool` could look for an environmental variable named `PROTOTOOL_GROUP_DEF` that would point to a YAML file that would configure a set of groups.

**Comment by peter-edge** [comment]
Would a “scratch” lint group help? Then you can just specify your rules in “rules: add:”

**Comment by peter-edge** [comment]
See #384.

**Comment by peter-edge** [comment]
Fixed on dev:

```yaml
lint:
  group: empty
  rules:
    add:
      - MESSAGE_NAMES_CAMEL_CASE
      - MESSAGE_NAMES_CAPITALIZED
```
