### ISSUE TITLE
GRPC plugin for Java doesn't exist (Stub files are not generated)

### ISSUE THREAD

**Issue by AlexGII** [uber/prototool#435]
Hey, I'm very excited about your project it has to be useful for many other companies, but
I have met some issue around java proto generation I can't see Stub grpc classes.

step for reproducing:

1. proto file example 
```
syntax = "proto3";
package com.my.v1;

option java_multiple_files = true;
option java_outer_classname = "MyApiProto";
option java_package = "com.my.v1";

// Interface exported by the server.
service MyAPI {
    // Bi-directional streaming RPC.
    rpc ShowMagic(stream MagicRequest) returns (stream MagicResponse) {}
}

message MagicRequest {
    int64 magic_id = 1;
}

message MagicResponse {
    bytes magic = 1;
}
```

2. prototool.yaml
```
protoc:
  # The Protobuf version to use from https://github.com/protocolbuffers/protobuf/releases.
  # By default use 3.6.1.
  # You probably want to set this to make your builds completely reproducible.
  version: 3.6.1

# Code generation directives.
generate:
  # The list of plugins.
  plugins:
    - name: java
      output: gen/java
    - name: python
      output: gen/python
    - name: grpc_python
      path: grpc_python_plugin
      output: gen/python
```
3. docker run --rm -u 501:20 -v your_folder:/work uber/prototool:1.6.0 prototool generate
everything has to be ok, but in /gen/com/my/v1/ you can find only:
```
MagicRequest.java		MagicResponseOrBuilder.java
MagicRequestOrBuilder.java	MyApiProto.java
MagicResponse.java
```
I expect also to find **MagicAPIGrpc.java**

from my investigation, we need to add one more plugin as python has grpc_python_plugin, but for JAVA.
`DEBUG	running protoc	{"command": "/usr/bin/protoc -I /usr/include -I /work --grpc_python_out=/work/gen/python --plugin=protoc-gen-grpc_python=/usr/bin/grpc_python_plugin /work/slice/pb/sma/v1/sma_api.proto"}`

as a result, I expect something like in the example below
**prototool.yaml**
```
plugins:
    - name: java
      output: gen/java
    - name: grpc_java
      path: grpc_java_plugin
      output: gen/java
```
