### ISSUE TITLE
not generating import_path with go modules

### ISSUE THREAD

**Issue by bilemon** [uber/prototool#451]
**Problem Overview** The generated golang files have relative imports rather than "absolute" module imports. Consequently, the import statements fail and the various packages cannot find each other.

If I manually append the base module path to all the import statements, it clearly works...but that's obviously not feasible at scale.

I'm using prototool in a project outside of $GOPATH following the (relatively) new [go modules](https://github.com/golang/go/wiki/Modules) scheme.

That being said, I have tried setting the project up in the classic convention (aka in $GOPATH), but that also fails to append my base directory.

I'm fairly certain I'm just misusing the tool, but I have not been able to figure out what I'm doing incorrectly. I was under the impression that specifying the `import_path` was only useful for resolving issues with plugins, but then I added it in a moment of "why not?" to see if it would append my desired path. Obviously, that didn't work.

**Expected**
I expect the generated code to have imports as follows:

```
package foov1

import (
    "code.mysite.com/source/example-apis.git/foo/type/v1"
)
```

**Actual**
I am seeing relative import paths

```
import (
    "foo/type/v1"
)
```

My prototool.yaml

```
protoc:
  version: 3.7.1
lint:
  group: uber2

create:
  packages:
    - directory: .
      name: demo

generate:
  go_options:
    import_path: code.mysite.com/source/example-apis.git

  plugins:
    - name: go
      output: ../.gen/go
      flags: plugins=grpc
```

**Comment by peter-edge** [comment]
I can't see what is wrong without seeing your actual Protobuf files - Prototool handles this correctly, I can help if you post your actual Protobuf files and config somewhere though.

**Comment by peter-edge** [comment]
Actually nevermind, I do see the problem - you have not set the `type` field for `plugins`:

```yaml
 plugins:
    - name: go
      type: go
      output: ../.gen/go
      flags: plugins=grpc
```

This should solve it.
