### ISSUE TITLE
Can support common environment variables in prototool.yaml

### ISSUE THREAD

**Issue by wja513** [uber/prototool#458]
Like this:
```yaml
protoc:
  version: 3.7.1
  includes:
    - ${GOPATH}/src
    - ${C_INCLUDE_PATH} #/usr/local/include
...
```
