### ISSUE TITLE
option flag for protoc plugin does not work

### ISSUE THREAD

**Issue by Dr-Evans** [uber/prototool#471]
[protoc-gen-doc](https://github.com/pseudomuto/protoc-gen-doc) allows for a `doc_opt` field - https://github.com/pseudomuto/protoc-gen-doc#simple-usage 

I've written the following yaml using the `plugins.flags` field outlined here https://github.com/uber/prototool/issues/329:

```
# ...

generate:
  go_options:
    import_path: github.com/dr_evans/foobar

  plugins:
    - name: go
      type: go
      output: .

    - name: doc
      flags: doc_opt=markdown
      output: ./docs
```

However, it appears that the flags are being added to the output, as evidenced by running `prototool generate --debug` (notice `--doc_out=doc_opt=markdown\\n`)

```
2019-06-17T23:18:01.114-0700	DEBUG	running protoc	{"command": "/Users/dr_evans/Library/Caches/prototool/Darwin/x86_64/protobuf/3.8.0/bin/protoc -I /Users/dr_evans/Library/Caches/prototool/Darwin/x86_64/protobuf/3.8.0/include -I /Users/dr_evans/go/src/github.com/dr_evans/foobar --doc_out=doc_opt=markdown\\n doc_out=./docs:/Users/nevans/go/src/github.com/dr_evans/foobar /Users/nevans/go/src/github.com/dr_evans/foobar/rpc/foo_api.proto"}
```

Apologies if I am specifying my `opt` incorrectly. Thanks in advance for your help!
