### ISSUE TITLE
[error] unable to convert org/zenithar/kingdom/realm/v1/RealmValidator.java to proto: template: go:2:14: executing \"go\" at <.InputPath>: can't evaluate field InputPath in type *pgs.msg

### ISSUE THREAD

**Issue by Zenithar** [uber/prototool#477]
Hello,

I'm using `github.com/envoyproxy/protoc-gen-validate@v0.1.0` with prototool v1.8.1 on Golang 1.12.7, this bug appears during the update to v0.1.0.

user_api.proto
```
syntax = "proto3";

package kingdom.user.v1;

option (gogoproto.benchgen_all) = true;
option (gogoproto.equal_all) = true;
option (gogoproto.marshaler_all) = true;
option (gogoproto.populate_all) = true;
option (gogoproto.sizer_all) = true;
option (gogoproto.testgen_all) = true;
option (gogoproto.unmarshaler_all) = true;
option csharp_namespace = "Kingdom.User.V1";
option go_package = "userv1";
option java_multiple_files = true;
option java_outer_classname = "UserApiProto";
option java_package = "org.zenithar.kingdom.user.v1";
option objc_class_prefix = "KUX";
option php_namespace = "Kingdom\\User\\V1";

import "github.com/envoyproxy/protoc-gen-validate/validate/validate.proto";
import "github.com/gogo/protobuf/gogoproto/gogo.proto";
import "google/protobuf/wrappers.proto";
import "kingdom/system/v1/system.proto";
import "kingdom/user/v1/user.proto";

// UserAPI manage user objects.
service UserAPI {
  // Create an user identity.
  rpc Create(CreateRequest) returns (CreateResponse);
  // Get an user by id.
  rpc Get(GetRequest) returns (GetResponse);
  // Update user attributes.
  rpc Update(UpdateRequest) returns (UpdateResponse);
  // Delete an user by id.
  rpc Delete(DeleteRequest) returns (DeleteResponse);
  // Search for user identity.
  rpc Search(SearchRequest) returns (SearchResponse);
  // Authenticate user identity.
  rpc Authenticate(AuthenticateRequest) returns (AuthenticateResponse);
}

// -----------------------------------------------------------------------------

message CreateRequest {
  string realm_id = 1 [
    (validate.rules).string = {
      pattern: "^[0-9A-Za-z]+$"
      len: 32
    }
  ];
  string principal = 2 [(validate.rules).string.pattern = "^[\x00-\x7F]+$"];
  string secret = 3 [(validate.rules).string.pattern = "^[\x00-\x7F]+$"];
}

message GetRequest {
  string realm_id = 1 [
    (validate.rules).string = {
      pattern: "^[0-9A-Za-z]+$"
      len: 32
    }
  ];
  string user_id = 2 [
    (validate.rules).string = {
      pattern: "^[0-9A-Za-z]+$"
      len: 32
    }
  ];
}

message UpdateRequest {
  string realm_id = 1 [
    (validate.rules).string = {
      pattern: "^[0-9A-Za-z]+$"
      len: 32
    }
  ];
  string user_id = 2 [
    (validate.rules).string = {
      pattern: "^[0-9A-Za-z]+$"
      len: 32
    }
  ];
  google.protobuf.StringValue secret = 3;
}

message DeleteRequest {
  string realm_id = 1 [
    (validate.rules).string = {
      pattern: "^[0-9A-Za-z]+$"
      len: 32
    }
  ];
  string user_id = 2 [
    (validate.rules).string = {
      pattern: "^[0-9A-Za-z]+$"
      len: 32
    }
  ];
}

message SearchRequest {
  uint32 page = 1;
  uint32 per_page = 2;
  repeated string sorts = 3;
  google.protobuf.StringValue cursor = 4;
  google.protobuf.StringValue realm_id = 5 [
    (validate.rules).string = {
      pattern: "^[0-9A-Za-z]+$"
      len: 32
    }
  ];
  google.protobuf.StringValue user_id = 6 [
    (validate.rules).string = {
      pattern: "^[0-9A-Za-z]+$"
      len: 32
    }
  ];
  google.protobuf.StringValue principal = 7;
}

message AuthenticateRequest {
  string realm_id = 1;
  string principal = 2;
  string secret = 3;
}

message CreateResponse {
  .kingdom.system.v1.Error error = 1;
  User entity = 2;
}

message GetResponse {
  .kingdom.system.v1.Error error = 1;
  User entity = 2;
}

message UpdateResponse {
  .kingdom.system.v1.Error error = 1;
  User entity = 2;
}

message DeleteResponse {
  .kingdom.system.v1.Error error = 1;
}

message SearchResponse {
  .kingdom.system.v1.Error error = 1;
  uint32 total = 2;
  uint32 per_page = 3;
  uint32 count = 4;
  uint32 current_page = 5;
  google.protobuf.StringValue next_cursor = 6;
  repeated User members = 7;
}

message AuthenticateResponse {
  .kingdom.system.v1.Error error = 1;
}
```

And prototool.yaml

````
protoc:
  # Additional paths to include with -I to protoc.
  # By default, the directory of the config file is included,
  # or the current directory if there is no config file.
  includes:
    - ../../vendor
    - ../../tools/vendor

  # If not set, compile will fail if there are unused imports.
  # Setting this will ignore unused imports.
  allow_unused_imports: false

lint:
  group: uber2
  file_header:
    path: ../../LICENSE
  java_package_prefix: org.zenithar
generate:
  go_options:
    import_path: go.zenithar.org/kingdom/pkg/protocol
  plugins:
    - name: gogo
      type: gogo
      flags: plugins=grpc
      output: ../gen/go
    - name: validate
      type: gogo
      flags: lang=gogo
      output: ../gen/go
    - name: cobra
      type: gogo
      output: ../gen/go
    - name: mock
      type: gogo
      output: ../gen/go

```

Crash on protoc-gen-validate.

If called directly, it successfully generates the file.
`protoc -I ./vendor -I ./tools/vendor -I pkg/protocol -I pkg/protocol/kingdom/user/v1 --validate_out="lang=gogo:pkg/gen/go" pkg/protocol/kingdom/user/v1/user_api.proto`
