### ISSUE TITLE
Support generating ruby gRPC

### ISSUE THREAD

**Issue by qiuyuzhou** [uber/prototool#481]
Below is how to generate grpc files for ruby in the official grpc document.

```
$ grpc_tools_ruby_protoc -I ../protos --ruby_out=lib --grpc_out=lib ../protos/helloworld.proto
```

The `grpc_tools_ruby_protoc` is a ruby script which it content is [here](https://github.com/grpc/grpc/blob/master/src/ruby/tools/bin/grpc_tools_ruby_protoc).

So the actual command line to call `protoc` is similar to this:
```
$ protoc --plugin=protoc-gen-grpc=grpc_ruby_plugin -I ../protos --ruby_out=lib --grpc_out=lib ../protos/helloworld.proto
```
It give a plugin flag to override the plugin command file name.

Suggest adding a `PluginFlag` attribute to the struct `GenPlugin` in order to support set `--plugin` flag for the `protoc`.

**Comment by smaye81** [comment]
This is actually already supported via the plugin config.  Take a look at `etc/config/example/prototool.yaml`.  The `path` optional override should do what you need.  Something like:

```
- name: grpc
   output: gen/proto/ruby
   path: /path/to/your/grpc_tools_ruby_protoc
```

**Comment by qiuyuzhou** [comment]
Thanks. After do some researching on the `path`, I end with this:
```
generate:
  plugins:
    - name: ruby
      output: ../gen/ruby
    - name: grpc
      output: ../gen/ruby
      path: grpc_ruby_plugin
```
