### ISSUE TITLE
Passing multiple parameters to protoc-gen-ts

### ISSUE THREAD

**Issue by soichisumi** [uber/prototool#486]
I want to use protoc-gen-ts with prototools, but prototool seems to accept only one string to flags parameter on prototool.yaml.
ref: https://github.com/uber/prototool/blob/dev/internal/settings/settings.go#L265

Is there any way to pass multiple flags to protoc plugin?

the command which I want to run:
```
protoc  \
     --plugin=protoc-gen-ts=./node_modules/.bin/protoc-gen-ts \
     --js_out=import_style=commonjs,binary:./src/proto \
     --ts_out=service=true:./src/proto \
     -I ./proto \
      proto/*.proto```

the prototool.yaml which I am using:
```
protoc:
  version: 3.8.0
generate:
  plugins:
    - name: ts
      flags: "--plugin=protoc-gen-ts --js_out=import_style=commonjs,binary --ts_out=service=true"
      output: ./gen/ts

```

**Comment by smaye81** [comment]
Check out https://github.com/uber/prototool/blob/dev/etc/config/example/prototool.yaml#L159 for an example on this.

You could do something like this:

```
generate:
  plugins:
    - name: ts
      flags: service=true
      output: gen/ts
      path: node_modules/.bin/protoc-gen-ts
    - name: js
      flags: import_style=commonjs,binary
      output: gen/js
```
