### ISSUE TITLE
"format --fix" does not follow lint configuration

### ISSUE THREAD

**Issue by goodspark** [uber/prototool#488]
It appears that `format -f` does not apply the same checks as `lint` and `format -d`.

My `prototool.yaml` file:
```yaml
lint:
  group: uber2
  rules:
    remove:
      - FILE_OPTIONS_REQUIRE_CSHARP_NAMESPACE
      - FILE_OPTIONS_REQUIRE_GO_PACKAGE
      - FILE_OPTIONS_REQUIRE_JAVA_MULTIPLE_FILES
      - FILE_OPTIONS_REQUIRE_JAVA_OUTER_CLASSNAME
      - FILE_OPTIONS_REQUIRE_JAVA_PACKAGE
      - FILE_OPTIONS_REQUIRE_OBJC_CLASS_PREFIX
      - FILE_OPTIONS_REQUIRE_PHP_NAMESPACE
```

My `x/x.proto` file:
```proto
syntax = "proto3";

package x.v1;

// Hello.
message Blah {}
```

- `lint x/x.proto` passes
- `format -d x/x.proto` passes
- `format -f x/x.proto` fails and it outputs:

```proto
syntax = "proto3";

package x.v1;

option csharp_namespace = "X.V1";
option go_package = "xv1";
option java_multiple_files = true;
option java_outer_classname = "XProto";
option java_package = "com.x.v1";
option objc_class_prefix = "XXX";
option php_namespace = "X\\V1";

// Hello.
message Blah {}
```

Which is very inconsistent with the previous two commands.
