### ISSUE TITLE
Relative path support for binaries

### ISSUE THREAD

**Issue by lukasmalkmus** [uber/prototool#493]
It would be great to have relative path support for `protoc-` binaries: https://github.com/uber/prototool/blob/4a300a9b2a55c7693516746ca22e72c9d00e7d26/etc/config/example/prototool.yaml#L159

I'm in need for this because a project installs its tools into a project local `bin` folder living in the root of the project while the `prototool.yaml` lives in `api/v1`. To use an absolute path isn't possible (multiple people with different location of the project on disc, CI, etc.)

So what I want to basically do is:

```yaml
protoc:
  plugins:
    - name: go
      type: go
      flags: plugins=grpc
      output: ../../internal/proto/v1
      path: ../../bin/protoc-gen-go
```

**Comment by smaye81** [comment]
This should already work.  What error are you seeing?  

To test this, I copied and renamed the `protoc-gen-gogo` plugin binary in my `$GOPATH` to be `protoc-gen-gogo-backup`.  I was able to generate files with the following config:

```
  plugins:
    - name: gogo
      type: gogo
      flags: plugins=grpc
      output: ../../gen/proto/go
      path: ../go/bin/protoc-gen-gogo-backup
```
