### ISSUE TITLE
V2 comment rule fails to recognize valid comments

### ISSUE THREAD

**Issue by Fleshgrinder** [uber/prototool#503]
I like Markdown because of its easy rules and plain text readability and I am sure others do to. I have the following simple comment:

```
// [ISO 4217] currency codes.
//
// [ISO 4217]: https://en.wikipedia.org/wiki/ISO_4217
enum Currency {
```

However, this fails the comment rule telling me:

```
fleshgrinder/v1/country.proto:16:1:Enum "Currency" needs a comment with a complete sentence that starts on the first line of the comment.
```

I agree with the sentiment of this but I already have a comment. Anything we can do about this? ☺️

**Comment by smaye81** [comment]
The simple fix for this would be to add the following to your prototool.yaml file:

```
ignores:
   - id: ENUM_FIELDS_HAVE_SENTENCE_COMMENTS
      files:
      - <path/to/your/file>
```
