### ISSUE TITLE
No service definition output for JS

### ISSUE THREAD

**Issue by mathewdbutton** [uber/prototool#527]
We're trying to use grpc_tools_node_protoc with prototool, we're getting the message definitions translated to JS but it doesn't seem to be generating the service definition so we can actually use the JS grpc client code in our project.

**prototool.yaml**
```yaml
protoc:
  version: 3.8.0

generate:
  plugins:
    - name: js
      flags: import_style=commonjs,binary
      output: ./test
      path: grpc_tools_node_protoc
```
brand_api.proto
```proto
syntax = "proto3";

package ibu.brand.v1;

// Handles Brands and their configuration.
service BrandAPI {
  // Get the Brand specified by the code.
  rpc GetBrand (GetBrandRequest) returns (GetBrandResponse) {}
}

// Request for getting a Brand
message GetBrandRequest {
  string brand_id = 1;
}

// Response for getting a Brand
message GetBrandResponse {
  string brand = 1;
}
```

Using Prototool with these files only results in `brand_api_pb.js` being generated, but if I try using grpc_tools_node_protoc by itself it will generate the service definition
`grpc_tools_node_protoc --js_out=import_style=commonjs,binary:./test --grpc_out=./test *.proto` 

It seems the only thing different between the two methods is that you can define a grpc_out flag for `grpc_tools_node_protoc` but not in the prototool.yml file. But I'm not quite sure what the flag or option looks like in the prototool.yml file

prototool version info:
```
Version:                 1.9.0
Default protoc version:  3.8.0
Go version:              go1.13.1
OS/Arch:                 darwin/amd64
```

Has anyone had any luck with prototool and JS? I'm guessing I'm completely missing some setting or not quite understanding some basic concept of how this is supposed to work. Any help would be greatly appreciated.

**Comment by jozefcipa** [comment]
Hey, it seems `js` only generates messages. To generate gRPC you need to edit your `prototool.yaml` as following

```
generate:
  plugins:
    - name: js
      output: ./test

    - name: grpc
      output: ./test
      path: grpc_tools_node_protoc_plugin
```

**Comment by mathewdbutton** [comment]
Thanks @jozefcipa, I'll give that a shot and see how I go

**Comment by jozefcipa** [comment]
sure, if it won't work, don't hesitate to contact me. I'm not saying I'm an expert, I actually learned about this project just very recently but I've spent the last couple of days just by trying to get it working and it seems it finally works for me 🎉

**Comment by mathewdbutton** [comment]
@jozefcipa Ohhhhhh hells yeah. I must have tried every combination except this one, thank you very much for your help.

For anyone else having trouble, this is what I'm currently using to get JS and TS to generate with prototool

```yaml
    - name: js
      flags: import_style=commonjs,binary
      output: ../../lib/packages/ibu-brand/
    - name: ts
      flags: service=true
      output: ../../lib/packages/ibu-brand/
      path: protoc-gen-ts
    - name: grpc
      output: ../../lib/packages/ibu-brand
      path: grpc_tools_node_protoc_plugin
```
