### ISSUE TITLE
go plugin gogo specified but no import path provided

### ISSUE THREAD

**Issue by jdevelop** [uber/prototool#563]
### prototool.yaml
```
protoc:
  version: 3.11.0
lint:
  group: google
  rules:
    remove:
      - SERVICE_NAMES_API_SUFFIX
      - SERVICE_NAMES_MATCH_FILE_NAME
      - REQUEST_RESPONSE_TYPES_ONLY_IN_FILE
generate:
  plugins:
    - name: js
      output: ./gen/js
      flags: import_style=commonjs,binary
    - name: gogo
      type: go
      flags: plugins=grpc
      output: ./gen/go
```

### `prototool lint idl/fingerprint.proto`
> go plugin gogo specified but no import path provided

### version
```
prototool version
Version:                 1.10.0
Default protoc version:  3.11.0
Go version:              go1.14.4
OS/Arch:                 linux/amd64
```

### protobuf version 3.12.0-1
