### ISSUE TITLE
How to specify a protoc command line argument in prototool.yaml?

### ISSUE THREAD

**Issue by sogartar** [uber/prototool#584]
I have a simple `prototool.yaml`

```
---
protoc:
    version: 3.13.0
lint:
    group: uber1

```

How can I add a command line option that is passed to `protoc`?
